
// Maestra ampliada: columnas comerciales/operativas
export const SAMPLE_PRODUCTS = [
  {
    sku: "PEY-001",
    sku_proveedor: "PB-001-10KG",
    ean: "7801234560012",
    nombre: "Alimento Gato Premium 10kg",
    marca: "PetBrand",
    especie: "Gato",
    categoria: "Alimento",
    subcategoria: "Premium",
    desc_breve: "Alimento completo para gatos adultos.",
    desc_larga: "Fórmula premium con proteínas de alta calidad y taurina. Recomendado por veterinarios.",
    imagenes: [
      "https://picsum.photos/seed/catfood1/400/400",
      "https://picsum.photos/seed/catfood2/400/400"
    ],
    proveedor: "Distribuidora Mascotas SA",
    disponible: true,
    uc: 120,
    dif: 0,
    costo_neto: 21990,
    costo_con_iva: 26168,
    psp: 34990,
    precio_referencia: 33990,
    pvp: 34990,
    pvp_sin_iva: 29487,
    margen_bruto_pct: 37.1,
    margen_con_iva_pct: 32.9,
    margen_bruto_clp: 13000,
    precio_min_estr_sin_iva: 28000,
    precio_min_estr_con_iva: 33320,
    tipo_venta: "Unitario",
    precio_descuento: null,
    margen_total: 34.5,
    venta_total: 4198800,
    margen_general: 1450000,
    peso_kg: 10,
    unidad_peso: "kg",
    dimensiones: "60 x 40 x 15 cm",
    fragil: false,
    estacionalidad: "Todo el año",
    recurrente: true,
    etiquetas_shopify: "premium,gato,10kg",
    activo_en_tienda: true,
    segmentacion_ticket: "Alto",
    nivel_rotacion: "Alta",
    tipo_producto_consumo: "Consumible",
    observacion: ""
  },
  {
    sku: "PEY-002",
    sku_proveedor: "PB-002-3KG",
    ean: "7801234560029",
    nombre: "Alimento Perro Light 3kg",
    marca: "PetBrand",
    especie: "Perro",
    categoria: "Alimento",
    subcategoria: "Light",
    desc_breve: "Bajo en calorías para control de peso.",
    desc_larga: "Receta balanceada con fibra y L-carnitina para perros con sobrepeso.",
    imagenes: ["https://picsum.photos/seed/dogfood1/400/400"],
    proveedor: "Distribuidora Mascotas SA",
    disponible: true,
    uc: 80,
    dif: -2,
    costo_neto: 10990,
    costo_con_iva: 13078,
    psp: 18990,
    precio_referencia: 17990,
    pvp: 18990,
    pvp_sin_iva: 15916,
    margen_bruto_pct: 42.1,
    margen_con_iva_pct: 38.0,
    margen_bruto_clp: 8000,
    precio_min_estr_sin_iva: 15000,
    precio_min_estr_con_iva: 17850,
    tipo_venta: "Unitario",
    precio_descuento: null,
    margen_total: 39.2,
    venta_total: 1519200,
    margen_general: 595000,
    peso_kg: 3,
    unidad_peso: "kg",
    dimensiones: "40 x 25 x 12 cm",
    fragil: false,
    estacionalidad: "Todo el año",
    recurrente: true,
    etiquetas_shopify: "light,perro,3kg",
    activo_en_tienda: true,
    segmentacion_ticket: "Medio",
    nivel_rotacion: "Media",
    tipo_producto_consumo: "Consumible",
    observacion: ""
  },
  {
    sku: "PEY-003",
    sku_proveedor: "CP-001-5L",
    ean: "7801234560036",
    nombre: "Arena Aglomerante 5L",
    marca: "CleanPaws",
    especie: "Gato",
    categoria: "Higiene",
    subcategoria: "Arena",
    desc_breve: "Control de olores, rápida aglomeración.",
    desc_larga: "Arena mineral de alta absorción, neutraliza olores por 24h.",
    imagenes: ["https://picsum.photos/seed/litter1/400/400"],
    proveedor: "CleanPaws Chile",
    disponible: false,
    uc: 60,
    dif: 0,
    costo_neto: 5900,
    costo_con_iva: 7021,
    psp: 9990,
    precio_referencia: 9490,
    pvp: 9990,
    pvp_sin_iva: 8395,
    margen_bruto_pct: 41.1,
    margen_con_iva_pct: 34.7,
    margen_bruto_clp: 4090,
    precio_min_estr_sin_iva: 7900,
    precio_min_estr_con_iva: 9400,
    tipo_venta: "Unitario",
    precio_descuento: null,
    margen_total: 36.0,
    venta_total: 599400,
    margen_general: 215000,
    peso_kg: 5,
    unidad_peso: "L",
    dimensiones: "30 x 20 x 10 cm",
    fragil: false,
    estacionalidad: "Todo el año",
    recurrente: false,
    etiquetas_shopify: "arena,gato,aglomerante",
    activo_en_tienda: false,
    segmentacion_ticket: "Bajo",
    nivel_rotacion: "Alta",
    tipo_producto_consumo: "Consumible",
    observacion: "Reponer con próxima importación"
  },
  {
    sku: "PEY-004",
    sku_proveedor: "PF-TOY-045",
    ean: "7801234560043",
    nombre: "Rascador Mediano",
    marca: "PetFun",
    especie: "Gato",
    categoria: "Juguetes",
    subcategoria: "Rascadores",
    desc_breve: "Estructura de sisal resistente.",
    desc_larga: "Rascador con base antideslizante y poste de 60cm.",
    imagenes: ["https://picsum.photos/seed/scratcher/400/400"],
    proveedor: "PetFun LATAM",
    disponible: true,
    uc: 25,
    dif: 0,
    costo_neto: 15490,
    costo_con_iva: 18433,
    psp: 25990,
    precio_referencia: 24990,
    pvp: 25990,
    pvp_sin_iva: 21840,
    margen_bruto_pct: 41.0,
    margen_con_iva_pct: 34.1,
    margen_bruto_clp: 10500,
    precio_min_estr_sin_iva: 21000,
    precio_min_estr_con_iva: 24990,
    tipo_venta: "Unitario",
    precio_descuento: null,
    margen_total: 35.0,
    venta_total: 649750,
    margen_general: 227000,
    peso_kg: 1.8,
    unidad_peso: "kg",
    dimensiones: "45 x 35 x 10 cm",
    fragil: false,
    estacionalidad: "Todo el año",
    recurrente: false,
    etiquetas_shopify: "rascador,gato",
    activo_en_tienda: true,
    segmentacion_ticket: "Medio",
    nivel_rotacion: "Media",
    tipo_producto_consumo: "Durable",
    observacion: ""
  },
  {
    sku: "PEY-005",
    sku_proveedor: "HB-010-STD",
    ean: "7801234560050",
    nombre: "Snack Dental 7u",
    marca: "HappyBite",
    especie: "Perro",
    categoria: "Snacks",
    subcategoria: "Dental",
    desc_breve: "Ayuda a limpiar dientes y encías.",
    desc_larga: "Snacks con textura especial para reducir el sarro, recomendados a partir de 1 año.",
    imagenes: ["https://picsum.photos/seed/dental/400/400"],
    proveedor: "HappyBite",
    disponible: true,
    uc: 240,
    dif: 5,
    costo_neto: 2490,
    costo_con_iva: 2963,
    psp: 4990,
    precio_referencia: 4790,
    pvp: 4990,
    pvp_sin_iva: 4193,
    margen_bruto_pct: 50.1,
    margen_con_iva_pct: 45.2,
    margen_bruto_clp: 2500,
    precio_min_estr_sin_iva: 3800,
    precio_min_estr_con_iva: 4522,
    tipo_venta: "Unitario",
    precio_descuento: 4490,
    margen_total: 46.0,
    venta_total: 598800,
    margen_general: 276000,
    peso_kg: 0.25,
    unidad_peso: "kg",
    dimensiones: "18 x 10 x 4 cm",
    fragil: false,
    estacionalidad: "Todo el año",
    recurrente: true,
    etiquetas_shopify: "snack,perro,dental",
    activo_en_tienda: true,
    segmentacion_ticket: "Bajo",
    nivel_rotacion: "Alta",
    tipo_producto_consumo: "Consumible",
    observacion: ""
  },
];
